### ISSUE TITLE
help me to use fusepm

### ISSUE THREAD

**Issue by lehongwang** [bolav/fusepm#7]
I have tried
fusepm install https://github.com/MaxGraey/fuse-device
but got

AppData\Roaming\npm\node_modules\fusepm\lib\fusepm.js:53
                throw new Error('Found ' + foundfiles.length + ' unoproj files. Wanted ' + count);
                ^

Error: Found 0 unoproj files. Wanted 1

but Im already enter the command inside my project folder

then tried

fusepm install https://github.com/MaxGraey/fuse-device -p "D:\work\bmq\apps\bmq-internal\BMQInternal.unoproj"
install verify_local_unoproj.catch: Found 0 unoproj files. Wanted 1

then same error

please help

**Comment by bolav** [comment]
You need to run `fusepm` from a directory that contains a fuse project, and one `.unoproj`. If you have several you need to use the `--unoproj` parameter to specify which project you are using.
